Propose meetup types
lirantal/organising-awesome-meetups pull request #3
Opened 2019-05-11 17:59 UTC by danielmocan

2019-05-11 20:16 UTC, lirantal commented
Thanks @danielmocan, looks good!
I updated with some suggestions to rephrase the texts.

2019-05-11 20:18 UTC, lirantal requested changes

2019-05-11 20:18 UTC, lirantal commented on README.md
> +Its very easy to think about meetups in a clasical way: you have a speaker (or more) that comes and delivers a presentation and its nothing wrong with that. Its important to have different types of m
```suggestion
Meetups in their classic formats feature a speaker (or more) who delivers a presentation. However, meetups are a great ground to also feature different formats of learning. We propose:
```

2019-05-11 20:18 UTC, lirantal commented on README.md
> +- **workshop** - Coding during a meetup is very imporant, it helps retain more information because you have to get your hands dirty :)
```suggestion
- **workshop** - Writing code during a meetup helps attendees experience and learn through practical hands-on experience.
```

2019-05-11 20:18 UTC, lirantal commented on README.md
> +- **open talks** - You propose a topic, then the first thing at the begining of the meetup you ask people what subject releated to that topic they would like to be disscused. For this type of meetup
```suggestion
- **open talks** - A topic is selected for the meetup, and during the meetup event the attendees share a collection of subjects related to the topic proposed. A whiteboard helps facilitate this activity. Once enough subjects are gathered an open discussion with attendees can take place to share knowledge. An important aspect of this meetup is having a moderator for the conversation so it doesn't get side-tracked.
```

2019-05-11 20:18 UTC, lirantal commented on README.md
> +- social - For this meetup you dont have a specific subject, but its a good way for the members of you comunity to socialize. Most of the times during regular meetups there is little time to socializ
```suggestion
```

2019-05-11 20:18 UTC, lirantal commented on README.md
> +- social - For this meetup you dont have a specific subject, but its a good way for the members of you comunity to socialize. Most of the times during regular meetups there is little time to socializ
Since we aren't proposing anything new here I think we can leave this one out.

2019-05-12 06:12 UTC, danielmocan commented
Thank you @lirantal for helping me with the rephrase.

2019-05-12 08:19 UTC, lirantal approved these changes

2019-05-12 08:20 UTC, merged